Repository cisagov/CHIRP, pull requests merged in 2021-04, with the labels that each got.

#30 V1.0.4
  .github/workflows/bump_version.yaml
  .github/workflows/compile_test.yaml
  README.md
  chirp.py
  chirp/__main__.py
  chirp/common.py
  chirp/plugins/events/events.py
  chirp/plugins/yara/run.py
Labels: bug, improvement, version bump

#32 v1.0.5
  chirp.py
  chirp/__main__.py
  chirp/common.py
  chirp/load.py
  chirp/plugins/events/events.py
  chirp/plugins/events/evtx2json.py
  chirp/plugins/events/scan.py
  chirp/plugins/loader.py
  chirp/plugins/network/scan.py
  chirp/plugins/operators.py
  chirp/plugins/registry/registry.py
  chirp/plugins/registry/scan.py
  chirp/plugins/yara/run.py
  chirp/run.py
Labels: improvement

#36 v1.0.6
  README.md
  chirp/common.py
  chirp/plugins/network/network.py
  chirp/plugins/yara/run.py
Labels: improvement, version bump

#33 Non-zero Exit on IOC's Discovered in Non-interactive Mode
  README.md
  chirp.py
  chirp/__main__.py
  chirp/common.py
Labels: improvement

#40 V1.0.7
  README.md
  chirp.py
  chirp/__main__.py
  chirp/common.py
  chirp/plugins/events/events.py
  chirp/plugins/events/scan.py
  chirp/plugins/network/network.py
  chirp/plugins/network/scan.py
  chirp/plugins/registry/registry.py
  chirp/plugins/registry/scan.py
  chirp/plugins/yara/run.py
  chirp/run.py
  indicators/AA21-008A/AA21-008A.pdf
  indicators/AA21-008A/certexfil_powershell.yaml
  indicators/AA21-008A/certexfil_security.yaml
  indicators/AA21-008A/cisa_raindrop.yaml
  indicators/AA21-008A/cisa_solarfire.yaml
  indicators/AA21-008A/cisa_sunshuttle.yaml
  indicators/AA21-008A/cisa_teardrop.yaml
  indicators/AA21-008A/crowdstrike_rempack.yaml
  indicators/AA21-008A/crowdstrike_sunspot.yaml
  indicators/AA21-008A/fireeye_cosmicgale.yaml
  indicators/AA21-008A/fireeye_sunburst.yaml
  indicators/AA21-008A/iocs.yaml
  indicators/AA21-062A/AA21-062A.pdf
  indicators/AA21-062A/AA21062A.yaml
Labels: bug, documentation, improvement, version bump
